# LITHOLOGY_SETTING = [
#     "Доломит",
#     "Доломит глинистый",
#     "Доломит известковый",
#     "Доломит песчанистый",
#     "Доломит сульфатизированный",
#     "Доломит окремненный",
#     "Доломитовая брекчия",
#     "Известняк доломитовый",
#     "Известняк глинистый",
#     "Известняк",
#     "Известняк сульфатизированный",
#     "Известняк окремненный",
#     "Известняковая брекчия",
#     "Ангидрит",
#     "Ангидрит известняковый",
#     "Ангидрит доломитистый",
#     "Глинисто-карбонатная порода",
#     "Мергель",
#     "Мергель известковый",
#     "Мергель доломитовый",
#     "Аргиллит",
#     "Алевролит",
#     "Алевролит песчанистый",
#     "Песчаник",
#     "Песчаник глинистый",
#     "Песчаник алевритовый",
#     "Песчаник с примесью гравия",
#     "Гравелит",
#     "Брекчия",
#     "Глина",
#     "Гранит",
#     "Базальт",
#     "Гнейс",
#     "Сланец",
#     "Мрамор",
#     "Кварцит",
# ]
LITHOLOGY_SETTING = [
    "Dolomite",
    "Clayey Dolomite",
    "Limestone Dolomite",
    "Sandy Dolomite",
    "Sulfatized Dolomite",
    "Silicified Dolomite",
    "Dolomite Breccia",
    "Dolomitic Limestone",
    "Clayey Limestone",
    "Limestone",
    "Sulfatized Limestone",
    "Silicified Limestone",
    "Limestone Breccia",
    "Anhydrite",
    "Limestone Anhydrite",
    "Dolomitic Anhydrite",
    "Clay-carbonate Rock",
    "Marl",
    "Limestone Marl",
    "Dolomitic Marl",
    "Argillite",
    "Aleurolite",
    "Sandy Aleurolite",
    "Sandstone",
    "Clayey Sandstone",
    "Aleurolitic Sandstone",
    "Sandstone with Gravel Mix",
    "Gravelite",
    "Breccia",
    "Clay",
    "Granite",
    "Basalt",
    "Gneiss",
    "Slate",
    "Marble",
    "Quartzite",
]
