# Generated by Django 4.2.8 on 2023-12-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('group', models.CharField(max_length=100)),
                ('available_requests', models.IntegerField()),
                ('total_clicks', models.IntegerField()),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
