# Generated by Django 4.2.8 on 2023-12-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('access_rights', models.TextField(verbose_name='Права доступа')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AlterModelOptions(
            name='useraction',
            options={'verbose_name': 'Действие пользователя', 'verbose_name_plural': 'Действия пользователей'},
        ),
        migrations.AddField(
            model_name='useraction',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время действия'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='available_requests',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доступно запросов'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='total_clicks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего кликов'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_db.group', verbose_name='Группа'),
        ),
    ]
