# Generated by Django 4.2.8 on 2023-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0002_group_alter_useraction_options_useraction_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='group',
            field=models.CharField(choices=[('undefined', 'Неопределенный пользователь'), ('pro', 'PRO пользователь'), ('admin', 'Администратор')], default='undefined', max_length=50, verbose_name='Группа'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
