# app_db/management/commands/test_descriptions.py

TEST_DESCRIPTIONS = [
    ("ru", "Аргиллиты серые с зеленоватым оттенком, микрослоистые, с пологонаклонной косой слоистостью, подчеркнутой частыми, тонкими слойками алевролита темно-серого, мелкозернистого, глинистого, реже алевролита темно-серого мелко-крупнозернистого, плотные, с трещинами. Текстура участками нарушена деформацией осадка (смятием) и трещинами слоевых деформаций (микровзброс). Трещины субдиагональные, закрытого типа. Контакт с нижележащим слоем отчетливый, пологонаклонный, волнистый."),
    ("ru", "Аргиллиты серо-зеленые, микрослоистые, с косой слоистостью, тонкими слоями алевролита, плотные, с трещинами, текстура нарушена деформацией."),
    ("ru", "Доломиты коричневато-серые микро-тонкокристаллические, со структурой мадстоун, с редкими мелкими литокластами, с тонкими пологоволнистыми прослоями и линзовидными включениями серые микрокристаллические слабо глинистые, породы плотные, с трещинами, крепкие, слабо галитизированные, слабо сульфатизированные. Трещины тектонические, субвертикальные, протяженные, залечены галитом. Сульфатизация в виде мелких включений ангидрита. Контакт с подстилающим слоем четкий, слабоволнистый."),
    ("ru", "Доломиты коричневато-серые, микротонкокристаллические, структура мадстоун, редкие литокласты, пологоволнистые прослои, глинистые, галитизированные, сульфатизированные, трещины залечены галитом."),
    ("ru", "Песчаники светло-серые мелкозернистые, с примесью зерен средней псаммитовой размерности, с обильным карбонатным цементом, с пологоволнистой слоистостью, подчеркнутой частыми слойками серо-зеленого глинистого материала, подверженными пластической деформации, плотные, крепкие, со стяжениями пирита, слабо сульфатизированные. Сульфатизация представлена в виде мелких гнезд голубовато-серого ангидрита. Контакт с нижележащим слоем отчетливый, волнистый."),
    ("ru", "Песчаники светло-серые, мелкозернистые, среднепсаммитовые зерна, карбонатный цемент, пологоволнистая слоистость, глинистые слойки, сульфатизированные, пиритовые стяжения."),
    ("en", "Argillites are gray with a greenish tint, micro-laminated, with a gentle oblique layering emphasized by frequent, thin layers of dark gray, fine-grained, clayey aleurolite, and less often dark gray fine-to-coarse-grained aleurolite, dense, with cracks. The texture is locally disrupted by sediment deformation (folding) and cracks of layer deformation (micro throw-off). Cracks are subdiagonal, of a closed type. The contact with the underlying layer is distinct, gently sloping, wavy."),
    ("en", "Gray-green argillites, micro-laminated, with oblique layering, thin layers of aleurolite, dense, with cracks, texture disrupted by deformation."),
    ("en", "Brownish-gray dolomites, micro-fine crystalline, with a mudstone structure, rare small lithoclasts, thin gently wavy interlayers and lens-like inclusions of gray microcrystalline slightly clayey, rocks dense, with cracks, strong, weakly halitized, weakly sulfatized. Tectonic cracks are subvertical, extended, healed with halite. Sulfatization is in the form of small anhydrite inclusions. Contact with the underlying layer is clear, slightly wavy."),
    ("en", "Brownish-gray dolomites, micro-fine crystalline, mudstone structure, rare lithoclasts, gently wavy interlayers, clayey, halitized, sulfatized, cracks healed with halite."),
    ("en", "Light gray sandstones, fine-grained, with a mix of medium psammitic-sized grains, abundant carbonate cement, gently wavy layering, emphasized by frequent layers of gray-green clayey material, prone to plastic deformation, dense, strong, with pyrite concretions, weakly sulfatized. Sulfatization represented by small nests of bluish-gray anhydrite. Contact with the underlying layer is distinct, wavy."),
    ("en", "Light gray sandstones, fine-grained, medium psammitic grains, carbonate cement, gently wavy layering, clayey layers, sulfatized, pyrite concretions."),
]
